image: gcc:latest

stages:
  - build
  - test

before_script:
  - apt-get update && apt-get install -y cmake ninja-build

build:
  stage: build
  script:
    - cd ./build
    - cmake -G "MinGW Makefiles" ..
    - mingw32-make
test:
  stage: test
  script:
    - ./build/server &
    - sleep 2
    - curl http://localhost:8080 | grep "Server is up and running"
