
# @name responseBody
POST http://localhost:8080/project/add HTTP/1.1

{
    "repo" : "https://github.com/lou-16/krnl.git",
    "config" : {"baseImage": "alpine:latest"},
    "project_type" : "nodejs" 
}   

# @ref responseBody

POST http://localhost:8080/containers/create HTTP/1.1

{
    "id" : "0000019a8e0fd29f27d1",
    "config" : {"baseImage": "alpine:latest"}
}