

GET http://localhost:8080/ HTTP/1.1
# @name responseBody
POST http://localhost:8080/deployments/add HTTP/1.1

{
    "repo" : "https://github.com/lou-16/krnl.git",
    "config" : {"baseImage": "alpine:latest"},
    "project_type" : "nodejs" 
}   

# @ref responseBody

POST http://localhost:8080/deployments/containers/create HTTP/1.1

{
    "id" : "0000019b1957d87f96a4",
    "config" : {"baseImage": "alpine:latest"}
}